DROP ALL OBJECTS;

create TABLE IF NOT EXISTS mpa
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);
create TABLE IF NOT EXISTS films
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar      NOT NULL,
    description varchar(200) NOT NULL,
    releaseDate date,
    duration    integer,
    mpa_id      integer REFERENCES mpa (id)
);

create TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar NOT NULL,
    login    varchar NOT NULL,
    name     varchar,
    birthday timestamp
);
create TABLE IF NOT EXISTS likes
(
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE
);
create TABLE IF NOT EXISTS friendship_status
(
    status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status    varchar NOT NULL
);
create TABLE IF NOT EXISTS friendship
(
    user_id   INTEGER REFERENCES users (id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    status_id INTEGER REFERENCES friendship_status (status_id)
);
create TABLE IF NOT EXISTS genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar UNIQUE
);
create TABLE IF NOT EXISTS genre_film
(
    genre_id INTEGER REFERENCES genres (id) ON DELETE CASCADE,
    film_id  INTEGER REFERENCES films (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);
